# Default configuration for riscv32-softmmu

# Uncomment the following lines to disable these optional devices:
# CONFIG_PCI_DEVICES=n
# CONFIG_TEST_DEVICES=n

# Boards are selected by default, uncomment to keep out of the build.
# CONFIG_SPIKE=n
# CONFIG_SIFIVE_E=n
# CONFIG_SIFIVE_U=n
# CONFIG_RISCV_VIRT=n
# CONFIG_OPENTITAN=n

# Xilinx
CONFIG_XILINX=y
CONFIG_SSI=y
CONFIG_I2C=y
CONFIG_XILINX_AXI=y
CONFIG_XILINX_SPI=y
CONFIG_XILINX_SPIPS=y
CONFIG_PTIMER=y
CONFIG_CADENCE=y
CONFIG_SI57X=y
CONFIG_REMOTE_PORT=y
CONFIG_SPLIT_IRQ=y
CONFIG_OR_IRQ=y

CONFIG_I3C=y
CONFIG_CADENCE=y
CONFIG_XILINX_IOMODULE_UART=y
CONFIG_XILINX_IOMODULE_PIT=y
CONFIG_XILINX_IOMODULE_GPI=y
CONFIG_XILINX_IOMODULE_GPO=y
CONFIG_XILINX_IOMODULE_INTC=y
CONFIG_XILINX_ETHLITE=y

CONFIG_XLNX_ZYNQMP=y
CONFIG_XLNX_VERSAL=y
CONFIG_XLNX_ZYNQMP_CSU=y
CONFIG_XLNX_VERSAL_PMC=y
CONFIG_REMOTE_PORT_PCI=y
CONFIG_XLNX_VERSAL2_ASU_AES=y
CONFIG_XLNX_VERSAL2_ASU_SHA=y
