# Default configuration for microblaze-softmmu

# Boards are selected by default, uncomment to keep out of the build.
# CONFIG_PETALOGIX_S3ADSP1800=n

CONFIG_PTIMER=y
CONFIG_PFLASH_CFI01=y
CONFIG_SERIAL=y
CONFIG_XILINX=y
CONFIG_XILINX_AXI=y
CONFIG_XILINX_SPI=y
CONFIG_XILINX_ETHLITE=y
CONFIG_SSI=y
CONFIG_SSI_M25P80=y
CONFIG_REMOTE_PORT=y
CONFIG_I2C=y
CONFIG_CAN_BUS=y
CONFIG_SI57X=y
CONFIG_SDHCI=y
CONFIG_SPLIT_IRQ=y
CONFIG_OR_IRQ=y
CONFIG_DWC_I3C=y
