system_ss.add(files([
  'parse.c',
  'legacy-memory-node-probe.c',
  'resolve.c',
  'factory.c',
  'create.c',
  'blockdev.c',
  'netdev.c',
  'chardev.c',
  'remote-port.c',
  'clock.c',
  'realize.c',
  'legacy-mmap-iface.c',
  'memory-map.c',
  'gpio-legacy-resolve.c',
  'gpio-resolve.c',
  'gpio-connect.c',
  'util.c',
  'proxy.c',
  'fdt-input-visitor.c',
  'legacy-helpers.c',
]))
