# Default configuration for microblazeel-softmmu

# Boards are selected by default, uncomment to keep out of the build.
# CONFIG_PETALOGIX_S3ADSP1800=n
# CONFIG_PETALOGIX_ML605=n
# CONFIG_XLNX_ZYNQMP_PMU=n
CONFIG_XILINX_IOMODULE_UART=y
CONFIG_XILINX_IOMODULE_PIT=y
CONFIG_XILINX_IOMODULE_GPI=y
CONFIG_XILINX_IOMODULE_GPO=y
CONFIG_XILINX_IOMODULE_INTC=y
CONFIG_XLNX_ZYNQMP_CSU=y
CONFIG_XLNX_ZYNQMP=y
CONFIG_XLNX_VERSAL_PMC=y
CONFIG_XLNX_VERSAL=y
CONFIG_ARASAN_NFC=y
CONFIG_SDHCI=y
CONFIG_SD=y
CONFIG_CADENCE=y
CONFIG_XILINX_SPIPS=y
CONFIG_ZYNQ_DEVCFG=y
CONFIG_PL011=y

# Xilinx
CONFIG_CAN_BUS=y
include ../microblaze-softmmu/default.mak
